// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	AccountID             string
	ProviderID            string
	UserID                string
	AccessToken           pgtype.Text
	RefreshToken          pgtype.Text
	IDToken               pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamp
	RefreshTokenExpiresAt pgtype.Timestamp
	Scope                 pgtype.Text
	Password              pgtype.Text
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}

type AuthEvent struct {
	ID          string
	UserID      string
	EventType   string
	IpAddress   pgtype.Text
	UserAgent   pgtype.Text
	CreatedAt   pgtype.Timestamp
	TargetType  pgtype.Text
	TargetID    pgtype.Text
	Reason      pgtype.Text
	BeforeState []byte
	AfterState  []byte
}

type Invitation struct {
	ID             string
	OrganizationID string
	Email          string
	Role           pgtype.Text
	TeamID         pgtype.Text
	Status         string
	ExpiresAt      pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	InviterID      string
	Token          pgtype.Text
	InvitedUserID  pgtype.Text
	AcceptedAt     pgtype.Timestamp
}

type Member struct {
	ID             string
	OrganizationID string
	UserID         string
	Role           string
	CreatedAt      pgtype.Timestamp
}

type Organization struct {
	ID        string
	Name      string
	Slug      string
	Logo      pgtype.Text
	CreatedAt pgtype.Timestamp
	Metadata  pgtype.Text
	DeletedAt pgtype.Timestamp
}

type Session struct {
	ID                   string
	ExpiresAt            pgtype.Timestamp
	Token                string
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	IpAddress            pgtype.Text
	UserAgent            pgtype.Text
	UserID               string
	ImpersonatedBy       pgtype.Text
	ActiveOrganizationID pgtype.Text
	ActiveTeamID         pgtype.Text
	ImpersonationReason  pgtype.Text
}

type Team struct {
	ID             string
	Name           string
	OrganizationID string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type TeamMember struct {
	ID        string
	TeamID    string
	UserID    string
	CreatedAt pgtype.Timestamp
}

type TwoFactor struct {
	ID          string
	UserID      string
	Secret      string
	BackupCodes string
	Enabled     bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type TwoFactorChallenge struct {
	ID        string
	Token     string
	UserID    string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Role          string
	Banned        pgtype.Bool
	BanReason     pgtype.Text
	BanExpires    pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
