// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `json:"id"`
	AccountID             string           `json:"accountId"`
	ProviderID            string           `json:"providerId"`
	UserID                string           `json:"userId"`
	AccessToken           pgtype.Text      `json:"accessToken"`
	RefreshToken          pgtype.Text      `json:"refreshToken"`
	IDToken               pgtype.Text      `json:"idToken"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refreshTokenExpiresAt"`
	Scope                 pgtype.Text      `json:"scope"`
	Password              pgtype.Text      `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"createdAt"`
	UpdatedAt             pgtype.Timestamp `json:"updatedAt"`
}

type AuthEvent struct {
	ID             string           `json:"id"`
	UserID         string           `json:"userId"`
	EventType      string           `json:"eventType"`
	IpAddress      pgtype.Text      `json:"ipAddress"`
	UserAgent      pgtype.Text      `json:"userAgent"`
	TargetType     pgtype.Text      `json:"targetType"`
	TargetID       pgtype.Text      `json:"targetId"`
	Reason         pgtype.Text      `json:"reason"`
	BeforeState    []byte           `json:"beforeState"`
	AfterState     []byte           `json:"afterState"`
	OrganizationID pgtype.Text      `json:"organizationId"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
}

type Invitation struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organizationId"`
	Email          string           `json:"email"`
	Role           pgtype.Text      `json:"role"`
	TeamID         pgtype.Text      `json:"teamId"`
	Status         string           `json:"status"`
	ExpiresAt      pgtype.Timestamp `json:"expiresAt"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	InviterID      string           `json:"inviterId"`
	Token          pgtype.Text      `json:"token"`
	InvitedUserID  pgtype.Text      `json:"invitedUserId"`
	AcceptedAt     pgtype.Timestamp `json:"acceptedAt"`
}

type Member struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organizationId"`
	UserID         string           `json:"userId"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
}

type Organization struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	Logo      pgtype.Text      `json:"logo"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	Metadata  pgtype.Text      `json:"metadata"`
	DeletedAt pgtype.Timestamp `json:"deletedAt"`
}

type Session struct {
	ID                   string           `json:"id"`
	ExpiresAt            pgtype.Timestamp `json:"expiresAt"`
	Token                string           `json:"token"`
	CreatedAt            pgtype.Timestamp `json:"createdAt"`
	UpdatedAt            pgtype.Timestamp `json:"updatedAt"`
	IpAddress            pgtype.Text      `json:"ipAddress"`
	UserAgent            pgtype.Text      `json:"userAgent"`
	UserID               string           `json:"userId"`
	ImpersonatedBy       pgtype.Text      `json:"impersonatedBy"`
	ImpersonationReason  pgtype.Text      `json:"impersonationReason"`
	ActiveOrganizationID pgtype.Text      `json:"activeOrganizationId"`
	ActiveTeamID         pgtype.Text      `json:"activeTeamId"`
}

type Team struct {
	ID             string           `json:"id"`
	Name           string           `json:"name"`
	OrganizationID string           `json:"organizationId"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
	Description    pgtype.Text      `json:"description"`
	LeadUserID     pgtype.Text      `json:"leadUserId"`
	ArchivedAt     pgtype.Timestamp `json:"archivedAt"`
}

type TeamMember struct {
	ID        string           `json:"id"`
	TeamID    string           `json:"teamId"`
	UserID    string           `json:"userId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type TwoFactor struct {
	ID          string           `json:"id"`
	UserID      string           `json:"userId"`
	Secret      string           `json:"secret"`
	BackupCodes string           `json:"backupCodes"`
	Enabled     bool             `json:"enabled"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

type TwoFactorChallenge struct {
	ID        string           `json:"id"`
	Token     string           `json:"token"`
	UserID    string           `json:"userId"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type User struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Email         string           `json:"email"`
	EmailVerified bool             `json:"emailVerified"`
	Image         pgtype.Text      `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
	Role          string           `json:"role"`
	Banned        bool             `json:"banned"`
	BanReason     pgtype.Text      `json:"banReason"`
	BanExpires    pgtype.Timestamp `json:"banExpires"`
	DeletedAt     pgtype.Timestamp `json:"deletedAt"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expiresAt"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
}
