// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptOrganizationInvitation(ctx context.Context, arg AcceptOrganizationInvitationParams) error
	AdminCancelOrganizationInvitation(ctx context.Context, arg AdminCancelOrganizationInvitationParams) (string, error)
	AdminCountAuditEvents(ctx context.Context, search string) (int32, error)
	AdminCountOrganizations(ctx context.Context, arg AdminCountOrganizationsParams) (int32, error)
	AdminCountOwnedOrganizations(ctx context.Context, userID string) (int32, error)
	AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int32, error)
	AdminCountUsersByRole(ctx context.Context, role string) (int32, error)
	AdminCreateOrganization(ctx context.Context, arg AdminCreateOrganizationParams) (Organization, error)
	AdminCreateOrganizationInvitation(ctx context.Context, arg AdminCreateOrganizationInvitationParams) (Invitation, error)
	AdminCreateUser(ctx context.Context, arg AdminCreateUserParams) (User, error)
	AdminDashboardMetrics(ctx context.Context) (AdminDashboardMetricsRow, error)
	AdminDeleteOrganizationMember(ctx context.Context, arg AdminDeleteOrganizationMemberParams) (Member, error)
	AdminDeletePendingOrganizationInvitations(ctx context.Context, arg AdminDeletePendingOrganizationInvitationsParams) error
	AdminDemoteOrganizationOwners(ctx context.Context, organizationID string) error
	AdminGetOrganization(ctx context.Context, id string) (Organization, error)
	AdminGetOrganizationMember(ctx context.Context, arg AdminGetOrganizationMemberParams) (Member, error)
	AdminGetUser(ctx context.Context, id string) (User, error)
	AdminListAuditEvents(ctx context.Context, arg AdminListAuditEventsParams) ([]AdminListAuditEventsRow, error)
	AdminListOrganizationInvitations(ctx context.Context, organizationID string) ([]AdminListOrganizationInvitationsRow, error)
	AdminListOrganizationMembers(ctx context.Context, organizationID string) ([]AdminListOrganizationMembersRow, error)
	AdminListOrganizations(ctx context.Context, arg AdminListOrganizationsParams) ([]AdminListOrganizationsRow, error)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	AdminRestoreOrganization(ctx context.Context, id string) (Organization, error)
	AdminRestoreUser(ctx context.Context, id string) (User, error)
	AdminSetUserBan(ctx context.Context, arg AdminSetUserBanParams) (User, error)
	AdminSoftDeleteOrganization(ctx context.Context, id string) (Organization, error)
	AdminSoftDeleteUser(ctx context.Context, id string) (User, error)
	AdminUpdateOrganization(ctx context.Context, arg AdminUpdateOrganizationParams) (Organization, error)
	AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error)
	AdminUpsertOrganizationMember(ctx context.Context, arg AdminUpsertOrganizationMemberParams) error
	AdminUpsertOrganizationOwner(ctx context.Context, arg AdminUpsertOrganizationOwnerParams) error
	AdminUserGrowth(ctx context.Context) ([]AdminUserGrowthRow, error)
	CountActiveUserSessions(ctx context.Context, userID string) (int32, error)
	CreateAuthEvent(ctx context.Context, arg CreateAuthEventParams) error
	CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) error
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error
	CreateImpersonatedSession(ctx context.Context, arg CreateImpersonatedSessionParams) (Session, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTwoFactorChallenge(ctx context.Context, arg CreateTwoFactorChallengeParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllUserSessions(ctx context.Context, userID string) error
	DeleteEmailVerification(ctx context.Context, id string) error
	DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error
	DeleteSession(ctx context.Context, token string) error
	DeleteTwoFactor(ctx context.Context, userID string) error
	DeleteTwoFactorChallenge(ctx context.Context, id string) error
	DeleteUserEmailVerifications(ctx context.Context, identifier string) error
	EnableTwoFactor(ctx context.Context, arg EnableTwoFactorParams) error
	GetActiveEmailVerification(ctx context.Context, value string) (GetActiveEmailVerificationRow, error)
	GetActiveOrganizationInvitation(ctx context.Context, arg GetActiveOrganizationInvitationParams) (GetActiveOrganizationInvitationRow, error)
	GetActivePasswordReset(ctx context.Context, value string) (GetActivePasswordResetRow, error)
	GetCredentialPasswordByUserID(ctx context.Context, userID string) (pgtype.Text, error)
	GetCredentialUserByEmail(ctx context.Context, lower string) (GetCredentialUserByEmailRow, error)
	GetPasswordResetUserByEmail(ctx context.Context, lower string) (GetPasswordResetUserByEmailRow, error)
	GetRecentEmailVerification(ctx context.Context, identifier string) (pgtype.Timestamp, error)
	GetSessionUser(ctx context.Context, token string) (GetSessionUserRow, error)
	GetTwoFactorByUserID(ctx context.Context, userID string) (TwoFactor, error)
	GetTwoFactorChallenge(ctx context.Context, token string) (GetTwoFactorChallengeRow, error)
	GetUserSignInActivity(ctx context.Context, userID string) ([]GetUserSignInActivityRow, error)
	ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error)
	MarkUserEmailVerified(ctx context.Context, id string) error
	Ping(ctx context.Context) (int32, error)
	RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (string, error)
	UpdateCredentialPassword(ctx context.Context, arg UpdateCredentialPasswordParams) error
	UpdateTwoFactorBackupCodes(ctx context.Context, arg UpdateTwoFactorBackupCodesParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertPendingTwoFactor(ctx context.Context, arg UpsertPendingTwoFactorParams) (TwoFactor, error)
}

var _ Querier = (*Queries)(nil)
