// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptOrganizationInvitation(ctx context.Context, arg AcceptOrganizationInvitationParams) error
	AddOrganizationRolePermission(ctx context.Context, arg AddOrganizationRolePermissionParams) error
	AddOrganizationTeamMember(ctx context.Context, arg AddOrganizationTeamMemberParams) (int64, error)
	AdminCancelOrganizationInvitation(ctx context.Context, arg AdminCancelOrganizationInvitationParams) (string, error)
	AdminCountAuditEvents(ctx context.Context, search string) (int32, error)
	AdminCountOrganizations(ctx context.Context, arg AdminCountOrganizationsParams) (int32, error)
	AdminCountOwnedOrganizations(ctx context.Context, userID string) (int32, error)
	AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int32, error)
	AdminCountUsersByRole(ctx context.Context, role string) (int32, error)
	AdminCreateOrganization(ctx context.Context, arg AdminCreateOrganizationParams) (Organization, error)
	AdminCreateOrganizationInvitation(ctx context.Context, arg AdminCreateOrganizationInvitationParams) (Invitation, error)
	AdminCreateUser(ctx context.Context, arg AdminCreateUserParams) (User, error)
	AdminDashboardMetrics(ctx context.Context) (AdminDashboardMetricsRow, error)
	AdminDeleteOrganizationMember(ctx context.Context, arg AdminDeleteOrganizationMemberParams) (Member, error)
	AdminDemoteOrganizationOwners(ctx context.Context, organizationID string) error
	AdminGetOrganization(ctx context.Context, id string) (Organization, error)
	AdminGetOrganizationMember(ctx context.Context, arg AdminGetOrganizationMemberParams) (Member, error)
	AdminGetUser(ctx context.Context, id string) (User, error)
	AdminListAuditEvents(ctx context.Context, arg AdminListAuditEventsParams) ([]AdminListAuditEventsRow, error)
	AdminListOrganizationInvitations(ctx context.Context, organizationID string) ([]AdminListOrganizationInvitationsRow, error)
	AdminListOrganizationMembers(ctx context.Context, organizationID string) ([]AdminListOrganizationMembersRow, error)
	AdminListOrganizations(ctx context.Context, arg AdminListOrganizationsParams) ([]AdminListOrganizationsRow, error)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	AdminRestoreOrganization(ctx context.Context, id string) (Organization, error)
	AdminRestoreUser(ctx context.Context, id string) (User, error)
	AdminSetUserBan(ctx context.Context, arg AdminSetUserBanParams) (User, error)
	AdminSoftDeleteOrganization(ctx context.Context, id string) (Organization, error)
	AdminSoftDeleteUser(ctx context.Context, id string) (User, error)
	AdminUpdateOrganization(ctx context.Context, arg AdminUpdateOrganizationParams) (Organization, error)
	AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error)
	AdminUpsertOrganizationMember(ctx context.Context, arg AdminUpsertOrganizationMemberParams) error
	AdminUpsertOrganizationOwner(ctx context.Context, arg AdminUpsertOrganizationOwnerParams) error
	AdminUserGrowth(ctx context.Context) ([]AdminUserGrowthRow, error)
	AssignOrganizationCustomRole(ctx context.Context, arg AssignOrganizationCustomRoleParams) (Member, error)
	BulkAddOrganizationTeamMembers(ctx context.Context, arg BulkAddOrganizationTeamMembersParams) (int64, error)
	BulkDeleteOrganizationTeamMembers(ctx context.Context, arg BulkDeleteOrganizationTeamMembersParams) (int64, error)
	CanAccessOrganizationTeam(ctx context.Context, arg CanAccessOrganizationTeamParams) (bool, error)
	ClearActiveTeamFromSessions(ctx context.Context, activeTeamID pgtype.Text) error
	ClearActiveTeamFromUserSessions(ctx context.Context, arg ClearActiveTeamFromUserSessionsParams) error
	ClearOrganizationFromUserSessions(ctx context.Context, arg ClearOrganizationFromUserSessionsParams) error
	CountActiveOrganizationMembersByIDs(ctx context.Context, arg CountActiveOrganizationMembersByIDsParams) (int32, error)
	CountActiveUserSessions(ctx context.Context, userID string) (int32, error)
	CountOrganizationAuditEvents(ctx context.Context, organizationID pgtype.Text) (int64, error)
	CountOrganizationOwners(ctx context.Context, organizationID string) (int32, error)
	CountTeamAuditEvents(ctx context.Context, arg CountTeamAuditEventsParams) (int64, error)
	CountUnreadUserNotifications(ctx context.Context, userID string) (int32, error)
	CreateAuthEvent(ctx context.Context, arg CreateAuthEventParams) error
	CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) error
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error
	CreateImpersonatedSession(ctx context.Context, arg CreateImpersonatedSessionParams) (Session, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOrganizationAuditEvent(ctx context.Context, arg CreateOrganizationAuditEventParams) error
	CreateOrganizationCustomRole(ctx context.Context, arg CreateOrganizationCustomRoleParams) (OrganizationRole, error)
	CreateOrganizationTeam(ctx context.Context, arg CreateOrganizationTeamParams) (Team, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTwoFactorChallenge(ctx context.Context, arg CreateTwoFactorChallengeParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllUserSessions(ctx context.Context, userID string) error
	DeleteEmailVerification(ctx context.Context, id string) error
	DeleteOrganizationCustomRole(ctx context.Context, arg DeleteOrganizationCustomRoleParams) (int64, error)
	DeleteOrganizationMember(ctx context.Context, arg DeleteOrganizationMemberParams) (Member, error)
	DeleteOrganizationMemberTeams(ctx context.Context, arg DeleteOrganizationMemberTeamsParams) error
	DeleteOrganizationTeam(ctx context.Context, arg DeleteOrganizationTeamParams) (Team, error)
	DeleteOrganizationTeamMember(ctx context.Context, arg DeleteOrganizationTeamMemberParams) (int64, error)
	DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error
	DeleteSession(ctx context.Context, token string) error
	DeleteTwoFactor(ctx context.Context, userID string) error
	DeleteTwoFactorChallenge(ctx context.Context, id string) error
	DeleteUserEmailVerifications(ctx context.Context, identifier string) error
	EnableTwoFactor(ctx context.Context, arg EnableTwoFactorParams) error
	GetActiveEmailVerification(ctx context.Context, value string) (GetActiveEmailVerificationRow, error)
	GetActivePasswordReset(ctx context.Context, value string) (GetActivePasswordResetRow, error)
	GetCredentialPasswordByUserID(ctx context.Context, userID string) (pgtype.Text, error)
	GetCredentialUserByEmail(ctx context.Context, lower string) (GetCredentialUserByEmailRow, error)
	GetOrganizationCustomRole(ctx context.Context, arg GetOrganizationCustomRoleParams) (OrganizationRole, error)
	GetOrganizationInvitationForAcceptance(ctx context.Context, arg GetOrganizationInvitationForAcceptanceParams) (GetOrganizationInvitationForAcceptanceRow, error)
	GetOrganizationMembership(ctx context.Context, arg GetOrganizationMembershipParams) (GetOrganizationMembershipRow, error)
	GetOrganizationTeam(ctx context.Context, arg GetOrganizationTeamParams) (Team, error)
	GetPasswordResetUserByEmail(ctx context.Context, lower string) (GetPasswordResetUserByEmailRow, error)
	GetPendingOrganizationInvitation(ctx context.Context, arg GetPendingOrganizationInvitationParams) (string, error)
	GetRecentEmailVerification(ctx context.Context, identifier string) (pgtype.Timestamp, error)
	GetSessionUser(ctx context.Context, token string) (GetSessionUserRow, error)
	GetTwoFactorByUserID(ctx context.Context, userID string) (TwoFactor, error)
	GetTwoFactorChallenge(ctx context.Context, token string) (GetTwoFactorChallengeRow, error)
	GetUserSignInActivity(ctx context.Context, userID string) ([]GetUserSignInActivityRow, error)
	ListAccessibleOrganizationTeams(ctx context.Context, arg ListAccessibleOrganizationTeamsParams) ([]ListAccessibleOrganizationTeamsRow, error)
	ListMemberCustomPermissions(ctx context.Context, arg ListMemberCustomPermissionsParams) ([]string, error)
	ListOrganizationAuditEvents(ctx context.Context, arg ListOrganizationAuditEventsParams) ([]ListOrganizationAuditEventsRow, error)
	ListOrganizationCustomRoles(ctx context.Context, organizationID string) ([]ListOrganizationCustomRolesRow, error)
	ListOrganizationInvitations(ctx context.Context, organizationID string) ([]ListOrganizationInvitationsRow, error)
	ListOrganizationMembers(ctx context.Context, organizationID string) ([]ListOrganizationMembersRow, error)
	ListOrganizationRolePermissionKeys(ctx context.Context, arg ListOrganizationRolePermissionKeysParams) ([]string, error)
	ListOrganizationTeamMembers(ctx context.Context, arg ListOrganizationTeamMembersParams) ([]ListOrganizationTeamMembersRow, error)
	ListOrganizationTeams(ctx context.Context, arg ListOrganizationTeamsParams) ([]ListOrganizationTeamsRow, error)
	ListTeamAuditEvents(ctx context.Context, arg ListTeamAuditEventsParams) ([]ListTeamAuditEventsRow, error)
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error)
	ListUserOrganizations(ctx context.Context, userID string) ([]ListUserOrganizationsRow, error)
	ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error)
	LockOrganizationForInvitation(ctx context.Context, id string) (string, error)
	MarkAllUserNotificationsRead(ctx context.Context, userID string) (int64, error)
	MarkUserEmailVerified(ctx context.Context, id string) error
	MarkUserNotificationRead(ctx context.Context, arg MarkUserNotificationReadParams) (Notification, error)
	Ping(ctx context.Context) (int32, error)
	ReplaceOrganizationRolePermissions(ctx context.Context, roleID string) error
	RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (string, error)
	SetOrganizationTeamArchived(ctx context.Context, arg SetOrganizationTeamArchivedParams) (Team, error)
	SetSessionActiveOrganization(ctx context.Context, arg SetSessionActiveOrganizationParams) error
	SetSessionActiveTeam(ctx context.Context, arg SetSessionActiveTeamParams) (int64, error)
	TransferOrganizationOwnership(ctx context.Context, arg TransferOrganizationOwnershipParams) error
	UpdateCredentialPassword(ctx context.Context, arg UpdateCredentialPasswordParams) error
	UpdateOrganizationCustomRole(ctx context.Context, arg UpdateOrganizationCustomRoleParams) (OrganizationRole, error)
	UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (Member, error)
	UpdateOrganizationTeam(ctx context.Context, arg UpdateOrganizationTeamParams) (Team, error)
	UpdateOrganizationWorkspace(ctx context.Context, arg UpdateOrganizationWorkspaceParams) (Organization, error)
	UpdateTwoFactorBackupCodes(ctx context.Context, arg UpdateTwoFactorBackupCodesParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertPendingTwoFactor(ctx context.Context, arg UpsertPendingTwoFactorParams) (TwoFactor, error)
}

var _ Querier = (*Queries)(nil)
