// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentialAccount = `-- name: CreateCredentialAccount :exec
INSERT INTO accounts (
    id,
    account_id,
    provider_id,
    user_id,
    password
) VALUES (
    $1,
    $2,
    'credential',
    $3,
    $4
)
`

type CreateCredentialAccountParams struct {
	ID        string
	AccountID string
	UserID    string
	Password  pgtype.Text
}

func (q *Queries) CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) error {
	_, err := q.db.Exec(ctx, createCredentialAccount,
		arg.ID,
		arg.AccountID,
		arg.UserID,
		arg.Password,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    expires_at,
    token,
    ip_address,
    user_agent,
    user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id, impersonated_by, active_organization_id, active_team_id
`

type CreateSessionParams struct {
	ID        string
	ExpiresAt pgtype.Timestamp
	Token     string
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	UserID    string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.ExpiresAt,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    name,
    email
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, email, email_verified, image, created_at, updated_at, role, banned, ban_reason, ban_expires
`

type CreateUserParams struct {
	ID    string
	Name  string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1
  AND token <> $2
`

type DeleteOtherUserSessionsParams struct {
	UserID string
	Token  string
}

func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.UserID, arg.Token)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getCredentialPasswordByUserID = `-- name: GetCredentialPasswordByUserID :one
SELECT password
FROM accounts
WHERE user_id = $1
  AND provider_id = 'credential'
LIMIT 1
`

func (q *Queries) GetCredentialPasswordByUserID(ctx context.Context, userID string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getCredentialPasswordByUserID, userID)
	var password pgtype.Text
	err := row.Scan(&password)
	return password, err
}

const getCredentialUserByEmail = `-- name: GetCredentialUserByEmail :one
SELECT
    users.id,
    users.name,
    users.email,
    users.email_verified,
    users.image,
    users.role,
    users.banned,
    users.ban_reason,
    users.ban_expires,
    accounts.password
FROM users
JOIN accounts ON accounts.user_id = users.id
WHERE lower(users.email) = lower($1)
  AND accounts.provider_id = 'credential'
LIMIT 1
`

type GetCredentialUserByEmailRow struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         pgtype.Text
	Role          string
	Banned        pgtype.Bool
	BanReason     pgtype.Text
	BanExpires    pgtype.Timestamp
	Password      pgtype.Text
}

func (q *Queries) GetCredentialUserByEmail(ctx context.Context, lower string) (GetCredentialUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCredentialUserByEmail, lower)
	var i GetCredentialUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
		&i.Password,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT
    sessions.id AS session_id,
    sessions.expires_at,
    sessions.created_at,
    sessions.updated_at,
    sessions.ip_address,
    sessions.user_agent,
    sessions.user_id,
    sessions.impersonated_by,
    sessions.active_organization_id,
    sessions.active_team_id,
    users.name AS user_name,
    users.email AS user_email,
    users.email_verified AS user_email_verified,
    users.image AS user_image,
    users.role AS user_role
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token = $1
  AND sessions.expires_at > (now() AT TIME ZONE 'UTC')
  AND coalesce(users.banned, FALSE) = FALSE
LIMIT 1
`

type GetSessionUserRow struct {
	SessionID            string
	ExpiresAt            pgtype.Timestamp
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	IpAddress            pgtype.Text
	UserAgent            pgtype.Text
	UserID               string
	ImpersonatedBy       pgtype.Text
	ActiveOrganizationID pgtype.Text
	ActiveTeamID         pgtype.Text
	UserName             string
	UserEmail            string
	UserEmailVerified    bool
	UserImage            pgtype.Text
	UserRole             string
}

func (q *Queries) GetSessionUser(ctx context.Context, token string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, token)
	var i GetSessionUserRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
		&i.UserName,
		&i.UserEmail,
		&i.UserEmailVerified,
		&i.UserImage,
		&i.UserRole,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT
    id,
    expires_at,
    created_at,
    updated_at,
    ip_address,
    user_agent,
    user_id,
    impersonated_by,
    active_organization_id,
    active_team_id,
    token = $2 AS is_current
FROM sessions
WHERE user_id = $1
  AND expires_at > (now() AT TIME ZONE 'UTC')
ORDER BY created_at DESC
`

type ListUserSessionsParams struct {
	UserID string
	Token  string
}

type ListUserSessionsRow struct {
	ID                   string
	ExpiresAt            pgtype.Timestamp
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	IpAddress            pgtype.Text
	UserAgent            pgtype.Text
	UserID               string
	ImpersonatedBy       pgtype.Text
	ActiveOrganizationID pgtype.Text
	ActiveTeamID         pgtype.Text
	IsCurrent            bool
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.UserID, arg.Token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.UserID,
			&i.ImpersonatedBy,
			&i.ActiveOrganizationID,
			&i.ActiveTeamID,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ping = `-- name: Ping :one
SELECT 1::integer AS value
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var value int32
	err := row.Scan(&value)
	return value, err
}

const revokeUserSession = `-- name: RevokeUserSession :one
DELETE FROM sessions
WHERE id = $1
  AND user_id = $2
  AND token <> $3
RETURNING id
`

type RevokeUserSessionParams struct {
	ID     string
	UserID string
	Token  string
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, revokeUserSession, arg.ID, arg.UserID, arg.Token)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateCredentialPassword = `-- name: UpdateCredentialPassword :exec
UPDATE accounts
SET
    password = $2,
    updated_at = (now() AT TIME ZONE 'UTC')
WHERE user_id = $1
  AND provider_id = 'credential'
`

type UpdateCredentialPasswordParams struct {
	UserID   string
	Password pgtype.Text
}

func (q *Queries) UpdateCredentialPassword(ctx context.Context, arg UpdateCredentialPasswordParams) error {
	_, err := q.db.Exec(ctx, updateCredentialPassword, arg.UserID, arg.Password)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    name = $2,
    image = $3,
    updated_at = (now() AT TIME ZONE 'UTC')
WHERE id = $1
RETURNING id, name, email, email_verified, image, created_at, updated_at, role, banned, ban_reason, ban_expires
`

type UpdateUserProfileParams struct {
	ID    string
	Name  string
	Image pgtype.Text
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.Image)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}
