// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUserSessions = `-- name: CountActiveUserSessions :one
SELECT count(*)::integer
FROM sessions
WHERE user_id = $1
  AND expires_at > (now() AT TIME ZONE 'UTC')
`

func (q *Queries) CountActiveUserSessions(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveUserSessions, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAuthEvent = `-- name: CreateAuthEvent :exec
INSERT INTO auth_events (
    id,
    user_id,
    event_type,
    ip_address,
    user_agent
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateAuthEventParams struct {
	ID        string
	UserID    string
	EventType string
	IpAddress pgtype.Text
	UserAgent pgtype.Text
}

func (q *Queries) CreateAuthEvent(ctx context.Context, arg CreateAuthEventParams) error {
	_, err := q.db.Exec(ctx, createAuthEvent,
		arg.ID,
		arg.UserID,
		arg.EventType,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const createCredentialAccount = `-- name: CreateCredentialAccount :exec
INSERT INTO accounts (
    id,
    account_id,
    provider_id,
    user_id,
    password
) VALUES (
    $1,
    $2,
    'credential',
    $3,
    $4
)
`

type CreateCredentialAccountParams struct {
	ID        string
	AccountID string
	UserID    string
	Password  pgtype.Text
}

func (q *Queries) CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) error {
	_, err := q.db.Exec(ctx, createCredentialAccount,
		arg.ID,
		arg.AccountID,
		arg.UserID,
		arg.Password,
	)
	return err
}

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO verifications (
    id,
    identifier,
    value,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateEmailVerificationParams struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamp
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, createEmailVerification,
		arg.ID,
		arg.Identifier,
		arg.Value,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    expires_at,
    token,
    ip_address,
    user_agent,
    user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id, impersonated_by, active_organization_id, active_team_id
`

type CreateSessionParams struct {
	ID        string
	ExpiresAt pgtype.Timestamp
	Token     string
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	UserID    string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.ExpiresAt,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
	)
	return i, err
}

const createTwoFactorChallenge = `-- name: CreateTwoFactorChallenge :exec
INSERT INTO two_factor_challenges (
    id,
    token,
    user_id,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateTwoFactorChallengeParams struct {
	ID        string
	Token     string
	UserID    string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateTwoFactorChallenge(ctx context.Context, arg CreateTwoFactorChallengeParams) error {
	_, err := q.db.Exec(ctx, createTwoFactorChallenge,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    name,
    email
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, email, email_verified, image, created_at, updated_at, role, banned, ban_reason, ban_expires
`

type CreateUserParams struct {
	ID    string
	Name  string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllUserSessions, userID)
	return err
}

const deleteEmailVerification = `-- name: DeleteEmailVerification :exec
DELETE FROM verifications
WHERE id = $1
`

func (q *Queries) DeleteEmailVerification(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerification, id)
	return err
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1
  AND token <> $2
`

type DeleteOtherUserSessionsParams struct {
	UserID string
	Token  string
}

func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.UserID, arg.Token)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const deleteTwoFactor = `-- name: DeleteTwoFactor :exec
DELETE FROM two_factors
WHERE user_id = $1
`

func (q *Queries) DeleteTwoFactor(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteTwoFactor, userID)
	return err
}

const deleteTwoFactorChallenge = `-- name: DeleteTwoFactorChallenge :exec
DELETE FROM two_factor_challenges
WHERE id = $1
`

func (q *Queries) DeleteTwoFactorChallenge(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTwoFactorChallenge, id)
	return err
}

const deleteUserEmailVerifications = `-- name: DeleteUserEmailVerifications :exec
DELETE FROM verifications
WHERE identifier = $1
`

func (q *Queries) DeleteUserEmailVerifications(ctx context.Context, identifier string) error {
	_, err := q.db.Exec(ctx, deleteUserEmailVerifications, identifier)
	return err
}

const enableTwoFactor = `-- name: EnableTwoFactor :exec
UPDATE two_factors
SET
    enabled = TRUE,
    backup_codes = $2
WHERE user_id = $1
`

type EnableTwoFactorParams struct {
	UserID      string
	BackupCodes string
}

func (q *Queries) EnableTwoFactor(ctx context.Context, arg EnableTwoFactorParams) error {
	_, err := q.db.Exec(ctx, enableTwoFactor, arg.UserID, arg.BackupCodes)
	return err
}

const getActiveEmailVerification = `-- name: GetActiveEmailVerification :one
SELECT
    verifications.id,
    verifications.identifier AS user_id
FROM verifications
JOIN users ON users.id = verifications.identifier
WHERE verifications.value = $1
  AND verifications.expires_at > (now() AT TIME ZONE 'UTC')
  AND users.email_verified = FALSE
LIMIT 1
FOR UPDATE
`

type GetActiveEmailVerificationRow struct {
	ID     string
	UserID string
}

func (q *Queries) GetActiveEmailVerification(ctx context.Context, value string) (GetActiveEmailVerificationRow, error) {
	row := q.db.QueryRow(ctx, getActiveEmailVerification, value)
	var i GetActiveEmailVerificationRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getActivePasswordReset = `-- name: GetActivePasswordReset :one
SELECT
    verifications.id,
    users.id AS user_id,
    accounts.password
FROM verifications
JOIN users ON lower(users.email) = lower(verifications.identifier)
JOIN accounts
    ON accounts.user_id = users.id
   AND accounts.provider_id = 'credential'
WHERE verifications.value = $1
  AND verifications.expires_at > (now() AT TIME ZONE 'UTC')
  AND coalesce(users.banned, FALSE) = FALSE
LIMIT 1
FOR UPDATE
`

type GetActivePasswordResetRow struct {
	ID       string
	UserID   string
	Password pgtype.Text
}

func (q *Queries) GetActivePasswordReset(ctx context.Context, value string) (GetActivePasswordResetRow, error) {
	row := q.db.QueryRow(ctx, getActivePasswordReset, value)
	var i GetActivePasswordResetRow
	err := row.Scan(&i.ID, &i.UserID, &i.Password)
	return i, err
}

const getCredentialPasswordByUserID = `-- name: GetCredentialPasswordByUserID :one
SELECT password
FROM accounts
WHERE user_id = $1
  AND provider_id = 'credential'
LIMIT 1
`

func (q *Queries) GetCredentialPasswordByUserID(ctx context.Context, userID string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getCredentialPasswordByUserID, userID)
	var password pgtype.Text
	err := row.Scan(&password)
	return password, err
}

const getCredentialUserByEmail = `-- name: GetCredentialUserByEmail :one
SELECT
    users.id,
    users.name,
    users.email,
    users.email_verified,
    users.image,
    users.role,
    users.banned,
    users.ban_reason,
    users.ban_expires,
    accounts.password,
    coalesce(two_factors.enabled, FALSE) AS two_factor_enabled
FROM users
JOIN accounts ON accounts.user_id = users.id
LEFT JOIN two_factors ON two_factors.user_id = users.id
WHERE lower(users.email) = lower($1)
  AND accounts.provider_id = 'credential'
LIMIT 1
`

type GetCredentialUserByEmailRow struct {
	ID               string
	Name             string
	Email            string
	EmailVerified    bool
	Image            pgtype.Text
	Role             string
	Banned           pgtype.Bool
	BanReason        pgtype.Text
	BanExpires       pgtype.Timestamp
	Password         pgtype.Text
	TwoFactorEnabled bool
}

func (q *Queries) GetCredentialUserByEmail(ctx context.Context, lower string) (GetCredentialUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCredentialUserByEmail, lower)
	var i GetCredentialUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
		&i.Password,
		&i.TwoFactorEnabled,
	)
	return i, err
}

const getPasswordResetUserByEmail = `-- name: GetPasswordResetUserByEmail :one
SELECT
    users.id,
    users.name,
    users.email
FROM users
JOIN accounts
    ON accounts.user_id = users.id
   AND accounts.provider_id = 'credential'
WHERE lower(users.email) = lower($1)
  AND coalesce(users.banned, FALSE) = FALSE
LIMIT 1
`

type GetPasswordResetUserByEmailRow struct {
	ID    string
	Name  string
	Email string
}

func (q *Queries) GetPasswordResetUserByEmail(ctx context.Context, lower string) (GetPasswordResetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetUserByEmail, lower)
	var i GetPasswordResetUserByEmailRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getRecentEmailVerification = `-- name: GetRecentEmailVerification :one
SELECT created_at
FROM verifications
WHERE identifier = $1
  AND created_at > (now() AT TIME ZONE 'UTC') - INTERVAL '60 seconds'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetRecentEmailVerification(ctx context.Context, identifier string) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getRecentEmailVerification, identifier)
	var created_at pgtype.Timestamp
	err := row.Scan(&created_at)
	return created_at, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT
    sessions.id AS session_id,
    sessions.expires_at,
    sessions.created_at,
    sessions.updated_at,
    sessions.ip_address,
    sessions.user_agent,
    sessions.user_id,
    sessions.impersonated_by,
    sessions.active_organization_id,
    sessions.active_team_id,
    users.name AS user_name,
    users.email AS user_email,
    users.email_verified AS user_email_verified,
    users.image AS user_image,
    users.role AS user_role
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token = $1
  AND sessions.expires_at > (now() AT TIME ZONE 'UTC')
  AND coalesce(users.banned, FALSE) = FALSE
LIMIT 1
`

type GetSessionUserRow struct {
	SessionID            string
	ExpiresAt            pgtype.Timestamp
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	IpAddress            pgtype.Text
	UserAgent            pgtype.Text
	UserID               string
	ImpersonatedBy       pgtype.Text
	ActiveOrganizationID pgtype.Text
	ActiveTeamID         pgtype.Text
	UserName             string
	UserEmail            string
	UserEmailVerified    bool
	UserImage            pgtype.Text
	UserRole             string
}

func (q *Queries) GetSessionUser(ctx context.Context, token string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, token)
	var i GetSessionUserRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
		&i.UserName,
		&i.UserEmail,
		&i.UserEmailVerified,
		&i.UserImage,
		&i.UserRole,
	)
	return i, err
}

const getTwoFactorByUserID = `-- name: GetTwoFactorByUserID :one
SELECT id, user_id, secret, backup_codes, enabled, created_at, updated_at
FROM two_factors
WHERE user_id = $1
`

func (q *Queries) GetTwoFactorByUserID(ctx context.Context, userID string) (TwoFactor, error) {
	row := q.db.QueryRow(ctx, getTwoFactorByUserID, userID)
	var i TwoFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.BackupCodes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTwoFactorChallenge = `-- name: GetTwoFactorChallenge :one
SELECT
    two_factor_challenges.id AS challenge_id,
    two_factor_challenges.user_id,
    two_factors.secret,
    two_factors.backup_codes,
    users.name,
    users.email,
    users.email_verified,
    users.image,
    users.role
FROM two_factor_challenges
JOIN two_factors
    ON two_factors.user_id = two_factor_challenges.user_id
   AND two_factors.enabled = TRUE
JOIN users ON users.id = two_factor_challenges.user_id
WHERE two_factor_challenges.token = $1
  AND two_factor_challenges.expires_at > (now() AT TIME ZONE 'UTC')
  AND coalesce(users.banned, FALSE) = FALSE
LIMIT 1
`

type GetTwoFactorChallengeRow struct {
	ChallengeID   string
	UserID        string
	Secret        string
	BackupCodes   string
	Name          string
	Email         string
	EmailVerified bool
	Image         pgtype.Text
	Role          string
}

func (q *Queries) GetTwoFactorChallenge(ctx context.Context, token string) (GetTwoFactorChallengeRow, error) {
	row := q.db.QueryRow(ctx, getTwoFactorChallenge, token)
	var i GetTwoFactorChallengeRow
	err := row.Scan(
		&i.ChallengeID,
		&i.UserID,
		&i.Secret,
		&i.BackupCodes,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
	)
	return i, err
}

const getUserSignInActivity = `-- name: GetUserSignInActivity :many
SELECT
    days.day::date AS day,
    count(auth_events.id)::integer AS sign_ins
FROM generate_series(
    ((now() AT TIME ZONE 'UTC')::date - interval '13 days')::date,
    (now() AT TIME ZONE 'UTC')::date,
    interval '1 day'
) AS days(day)
LEFT JOIN auth_events
    ON auth_events.user_id = $1
   AND auth_events.event_type IN ('login_success', 'two_factor_success')
   AND auth_events.created_at >= days.day
   AND auth_events.created_at < days.day + interval '1 day'
GROUP BY days.day
ORDER BY days.day
`

type GetUserSignInActivityRow struct {
	Day     pgtype.Date
	SignIns int32
}

func (q *Queries) GetUserSignInActivity(ctx context.Context, userID string) ([]GetUserSignInActivityRow, error) {
	rows, err := q.db.Query(ctx, getUserSignInActivity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSignInActivityRow
	for rows.Next() {
		var i GetUserSignInActivityRow
		if err := rows.Scan(&i.Day, &i.SignIns); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT
    id,
    expires_at,
    created_at,
    updated_at,
    ip_address,
    user_agent,
    user_id,
    impersonated_by,
    active_organization_id,
    active_team_id,
    token = $2 AS is_current
FROM sessions
WHERE user_id = $1
  AND expires_at > (now() AT TIME ZONE 'UTC')
ORDER BY created_at DESC
`

type ListUserSessionsParams struct {
	UserID string
	Token  string
}

type ListUserSessionsRow struct {
	ID                   string
	ExpiresAt            pgtype.Timestamp
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	IpAddress            pgtype.Text
	UserAgent            pgtype.Text
	UserID               string
	ImpersonatedBy       pgtype.Text
	ActiveOrganizationID pgtype.Text
	ActiveTeamID         pgtype.Text
	IsCurrent            bool
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.UserID, arg.Token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.UserID,
			&i.ImpersonatedBy,
			&i.ActiveOrganizationID,
			&i.ActiveTeamID,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified = TRUE
WHERE id = $1
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markUserEmailVerified, id)
	return err
}

const ping = `-- name: Ping :one
SELECT 1::integer AS value
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var value int32
	err := row.Scan(&value)
	return value, err
}

const revokeUserSession = `-- name: RevokeUserSession :one
DELETE FROM sessions
WHERE id = $1
  AND user_id = $2
  AND token <> $3
RETURNING id
`

type RevokeUserSessionParams struct {
	ID     string
	UserID string
	Token  string
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, revokeUserSession, arg.ID, arg.UserID, arg.Token)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateCredentialPassword = `-- name: UpdateCredentialPassword :exec
UPDATE accounts
SET
    password = $2,
    updated_at = (now() AT TIME ZONE 'UTC')
WHERE user_id = $1
  AND provider_id = 'credential'
`

type UpdateCredentialPasswordParams struct {
	UserID   string
	Password pgtype.Text
}

func (q *Queries) UpdateCredentialPassword(ctx context.Context, arg UpdateCredentialPasswordParams) error {
	_, err := q.db.Exec(ctx, updateCredentialPassword, arg.UserID, arg.Password)
	return err
}

const updateTwoFactorBackupCodes = `-- name: UpdateTwoFactorBackupCodes :exec
UPDATE two_factors
SET backup_codes = $2
WHERE user_id = $1
`

type UpdateTwoFactorBackupCodesParams struct {
	UserID      string
	BackupCodes string
}

func (q *Queries) UpdateTwoFactorBackupCodes(ctx context.Context, arg UpdateTwoFactorBackupCodesParams) error {
	_, err := q.db.Exec(ctx, updateTwoFactorBackupCodes, arg.UserID, arg.BackupCodes)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    name = $2,
    image = $3,
    updated_at = (now() AT TIME ZONE 'UTC')
WHERE id = $1
RETURNING id, name, email, email_verified, image, created_at, updated_at, role, banned, ban_reason, ban_expires
`

type UpdateUserProfileParams struct {
	ID    string
	Name  string
	Image pgtype.Text
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.Image)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}

const upsertPendingTwoFactor = `-- name: UpsertPendingTwoFactor :one
INSERT INTO two_factors (
    id,
    user_id,
    secret,
    backup_codes,
    enabled
) VALUES (
    $1,
    $2,
    $3,
    '[]',
    FALSE
)
ON CONFLICT (user_id) DO UPDATE
SET
    secret = excluded.secret,
    backup_codes = '[]',
    enabled = FALSE
RETURNING id, user_id, secret, backup_codes, enabled, created_at, updated_at
`

type UpsertPendingTwoFactorParams struct {
	ID     string
	UserID string
	Secret string
}

func (q *Queries) UpsertPendingTwoFactor(ctx context.Context, arg UpsertPendingTwoFactorParams) (TwoFactor, error) {
	row := q.db.QueryRow(ctx, upsertPendingTwoFactor, arg.ID, arg.UserID, arg.Secret)
	var i TwoFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.BackupCodes,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
