// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSession(ctx context.Context, token string) error
	GetCredentialUserByEmail(ctx context.Context, lower string) (GetCredentialUserByEmailRow, error)
	GetSessionUser(ctx context.Context, token string) (GetSessionUserRow, error)
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
