/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedAdminAuditRouteImport } from './routes/_protected/admin/audit'
import { Route as ProtectedAdminOrganizationsRouteImport } from './routes/_protected/admin/organizations'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/admin/users'
import { Route as ProtectedOrganizationsOrganizationSlugRouteImport } from './routes/_protected/organizations/$organizationSlug'
import { Route as ProtectedAdminOrganizationsOrganizationIdRouteImport } from './routes/_protected/admin/organizations/$organizationId'
import { Route as ProtectedOrganizationsOrganizationSlugIndexRouteImport } from './routes/_protected/organizations/$organizationSlug/index'
import { Route as ProtectedOrganizationsOrganizationSlugAuditRouteImport } from './routes/_protected/organizations/$organizationSlug/audit'
import { Route as ProtectedOrganizationsOrganizationSlugMembersRouteImport } from './routes/_protected/organizations/$organizationSlug/members'
import { Route as ProtectedOrganizationsOrganizationSlugSettingsRouteImport } from './routes/_protected/organizations/$organizationSlug/settings'
import { Route as ProtectedOrganizationsOrganizationSlugTeamsRouteImport } from './routes/_protected/organizations/$organizationSlug/teams'
import { Route as ProtectedOrganizationsOrganizationSlugTeamsIndexRouteImport } from './routes/_protected/organizations/$organizationSlug/teams/index'
import { Route as ProtectedOrganizationsOrganizationSlugTeamsTeamIdRouteImport } from './routes/_protected/organizations/$organizationSlug/teams/$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminAuditRoute = ProtectedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminOrganizationsRoute =
  ProtectedAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedOrganizationsOrganizationSlugRoute =
  ProtectedOrganizationsOrganizationSlugRouteImport.update({
    id: '/organizations/$organizationSlug',
    path: '/organizations/$organizationSlug',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminOrganizationsOrganizationIdRoute =
  ProtectedAdminOrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => ProtectedAdminOrganizationsRoute,
  } as any)
const ProtectedOrganizationsOrganizationSlugIndexRoute =
  ProtectedOrganizationsOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationsOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationsOrganizationSlugAuditRoute =
  ProtectedOrganizationsOrganizationSlugAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ProtectedOrganizationsOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationsOrganizationSlugMembersRoute =
  ProtectedOrganizationsOrganizationSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedOrganizationsOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationsOrganizationSlugSettingsRoute =
  ProtectedOrganizationsOrganizationSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedOrganizationsOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationsOrganizationSlugTeamsRoute =
  ProtectedOrganizationsOrganizationSlugTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => ProtectedOrganizationsOrganizationSlugRoute,
  } as any)
const ProtectedOrganizationsOrganizationSlugTeamsIndexRoute =
  ProtectedOrganizationsOrganizationSlugTeamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationsOrganizationSlugTeamsRoute,
  } as any)
const ProtectedOrganizationsOrganizationSlugTeamsTeamIdRoute =
  ProtectedOrganizationsOrganizationSlugTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => ProtectedOrganizationsOrganizationSlugTeamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof ProtectedAccountRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/admin/audit': typeof ProtectedAdminAuditRoute
  '/admin/organizations': typeof ProtectedAdminOrganizationsRouteWithChildren
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/organizations/$organizationSlug': typeof ProtectedOrganizationsOrganizationSlugRouteWithChildren
  '/admin/': typeof ProtectedAdminIndexRoute
  '/admin/organizations/$organizationId': typeof ProtectedAdminOrganizationsOrganizationIdRoute
  '/organizations/$organizationSlug/audit': typeof ProtectedOrganizationsOrganizationSlugAuditRoute
  '/organizations/$organizationSlug/members': typeof ProtectedOrganizationsOrganizationSlugMembersRoute
  '/organizations/$organizationSlug/settings': typeof ProtectedOrganizationsOrganizationSlugSettingsRoute
  '/organizations/$organizationSlug/teams': typeof ProtectedOrganizationsOrganizationSlugTeamsRouteWithChildren
  '/organizations/$organizationSlug/': typeof ProtectedOrganizationsOrganizationSlugIndexRoute
  '/organizations/$organizationSlug/teams/$teamId': typeof ProtectedOrganizationsOrganizationSlugTeamsTeamIdRoute
  '/organizations/$organizationSlug/teams/': typeof ProtectedOrganizationsOrganizationSlugTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/admin/audit': typeof ProtectedAdminAuditRoute
  '/admin/organizations': typeof ProtectedAdminOrganizationsRouteWithChildren
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/admin/organizations/$organizationId': typeof ProtectedAdminOrganizationsOrganizationIdRoute
  '/organizations/$organizationSlug/audit': typeof ProtectedOrganizationsOrganizationSlugAuditRoute
  '/organizations/$organizationSlug/members': typeof ProtectedOrganizationsOrganizationSlugMembersRoute
  '/organizations/$organizationSlug/settings': typeof ProtectedOrganizationsOrganizationSlugSettingsRoute
  '/organizations/$organizationSlug': typeof ProtectedOrganizationsOrganizationSlugIndexRoute
  '/organizations/$organizationSlug/teams/$teamId': typeof ProtectedOrganizationsOrganizationSlugTeamsTeamIdRoute
  '/organizations/$organizationSlug/teams': typeof ProtectedOrganizationsOrganizationSlugTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/admin/audit': typeof ProtectedAdminAuditRoute
  '/_protected/admin/organizations': typeof ProtectedAdminOrganizationsRouteWithChildren
  '/_protected/admin/users': typeof ProtectedAdminUsersRoute
  '/_protected/organizations/$organizationSlug': typeof ProtectedOrganizationsOrganizationSlugRouteWithChildren
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/admin/organizations/$organizationId': typeof ProtectedAdminOrganizationsOrganizationIdRoute
  '/_protected/organizations/$organizationSlug/audit': typeof ProtectedOrganizationsOrganizationSlugAuditRoute
  '/_protected/organizations/$organizationSlug/members': typeof ProtectedOrganizationsOrganizationSlugMembersRoute
  '/_protected/organizations/$organizationSlug/settings': typeof ProtectedOrganizationsOrganizationSlugSettingsRoute
  '/_protected/organizations/$organizationSlug/teams': typeof ProtectedOrganizationsOrganizationSlugTeamsRouteWithChildren
  '/_protected/organizations/$organizationSlug/': typeof ProtectedOrganizationsOrganizationSlugIndexRoute
  '/_protected/organizations/$organizationSlug/teams/$teamId': typeof ProtectedOrganizationsOrganizationSlugTeamsTeamIdRoute
  '/_protected/organizations/$organizationSlug/teams/': typeof ProtectedOrganizationsOrganizationSlugTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/users'
    | '/organizations/$organizationSlug'
    | '/admin/'
    | '/admin/organizations/$organizationId'
    | '/organizations/$organizationSlug/audit'
    | '/organizations/$organizationSlug/members'
    | '/organizations/$organizationSlug/settings'
    | '/organizations/$organizationSlug/teams'
    | '/organizations/$organizationSlug/'
    | '/organizations/$organizationSlug/teams/$teamId'
    | '/organizations/$organizationSlug/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/account'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/users'
    | '/admin'
    | '/admin/organizations/$organizationId'
    | '/organizations/$organizationSlug/audit'
    | '/organizations/$organizationSlug/members'
    | '/organizations/$organizationSlug/settings'
    | '/organizations/$organizationSlug'
    | '/organizations/$organizationSlug/teams/$teamId'
    | '/organizations/$organizationSlug/teams'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_protected/account'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/_protected/admin/audit'
    | '/_protected/admin/organizations'
    | '/_protected/admin/users'
    | '/_protected/organizations/$organizationSlug'
    | '/_protected/admin/'
    | '/_protected/admin/organizations/$organizationId'
    | '/_protected/organizations/$organizationSlug/audit'
    | '/_protected/organizations/$organizationSlug/members'
    | '/_protected/organizations/$organizationSlug/settings'
    | '/_protected/organizations/$organizationSlug/teams'
    | '/_protected/organizations/$organizationSlug/'
    | '/_protected/organizations/$organizationSlug/teams/$teamId'
    | '/_protected/organizations/$organizationSlug/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/audit': {
      id: '/_protected/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof ProtectedAdminAuditRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/organizations': {
      id: '/_protected/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof ProtectedAdminOrganizationsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/organizations/$organizationSlug': {
      id: '/_protected/organizations/$organizationSlug'
      path: '/organizations/$organizationSlug'
      fullPath: '/organizations/$organizationSlug'
      preLoaderRoute: typeof ProtectedOrganizationsOrganizationSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/organizations/$organizationId': {
      id: '/_protected/admin/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/admin/organizations/$organizationId'
      preLoaderRoute: typeof ProtectedAdminOrganizationsOrganizationIdRouteImport
      parentRoute: typeof ProtectedAdminOrganizationsRoute
    }
    '/_protected/organizations/$organizationSlug/': {
      id: '/_protected/organizations/$organizationSlug/'
      path: '/'
      fullPath: '/organizations/$organizationSlug/'
      preLoaderRoute: typeof ProtectedOrganizationsOrganizationSlugIndexRouteImport
      parentRoute: typeof ProtectedOrganizationsOrganizationSlugRoute
    }
    '/_protected/organizations/$organizationSlug/audit': {
      id: '/_protected/organizations/$organizationSlug/audit'
      path: '/audit'
      fullPath: '/organizations/$organizationSlug/audit'
      preLoaderRoute: typeof ProtectedOrganizationsOrganizationSlugAuditRouteImport
      parentRoute: typeof ProtectedOrganizationsOrganizationSlugRoute
    }
    '/_protected/organizations/$organizationSlug/members': {
      id: '/_protected/organizations/$organizationSlug/members'
      path: '/members'
      fullPath: '/organizations/$organizationSlug/members'
      preLoaderRoute: typeof ProtectedOrganizationsOrganizationSlugMembersRouteImport
      parentRoute: typeof ProtectedOrganizationsOrganizationSlugRoute
    }
    '/_protected/organizations/$organizationSlug/settings': {
      id: '/_protected/organizations/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/organizations/$organizationSlug/settings'
      preLoaderRoute: typeof ProtectedOrganizationsOrganizationSlugSettingsRouteImport
      parentRoute: typeof ProtectedOrganizationsOrganizationSlugRoute
    }
    '/_protected/organizations/$organizationSlug/teams': {
      id: '/_protected/organizations/$organizationSlug/teams'
      path: '/teams'
      fullPath: '/organizations/$organizationSlug/teams'
      preLoaderRoute: typeof ProtectedOrganizationsOrganizationSlugTeamsRouteImport
      parentRoute: typeof ProtectedOrganizationsOrganizationSlugRoute
    }
    '/_protected/organizations/$organizationSlug/teams/': {
      id: '/_protected/organizations/$organizationSlug/teams/'
      path: '/'
      fullPath: '/organizations/$organizationSlug/teams/'
      preLoaderRoute: typeof ProtectedOrganizationsOrganizationSlugTeamsIndexRouteImport
      parentRoute: typeof ProtectedOrganizationsOrganizationSlugTeamsRoute
    }
    '/_protected/organizations/$organizationSlug/teams/$teamId': {
      id: '/_protected/organizations/$organizationSlug/teams/$teamId'
      path: '/$teamId'
      fullPath: '/organizations/$organizationSlug/teams/$teamId'
      preLoaderRoute: typeof ProtectedOrganizationsOrganizationSlugTeamsTeamIdRouteImport
      parentRoute: typeof ProtectedOrganizationsOrganizationSlugTeamsRoute
    }
  }
}

interface ProtectedAdminOrganizationsRouteChildren {
  ProtectedAdminOrganizationsOrganizationIdRoute: typeof ProtectedAdminOrganizationsOrganizationIdRoute
}

const ProtectedAdminOrganizationsRouteChildren: ProtectedAdminOrganizationsRouteChildren =
  {
    ProtectedAdminOrganizationsOrganizationIdRoute:
      ProtectedAdminOrganizationsOrganizationIdRoute,
  }

const ProtectedAdminOrganizationsRouteWithChildren =
  ProtectedAdminOrganizationsRoute._addFileChildren(
    ProtectedAdminOrganizationsRouteChildren,
  )

interface ProtectedAdminRouteChildren {
  ProtectedAdminAuditRoute: typeof ProtectedAdminAuditRoute
  ProtectedAdminOrganizationsRoute: typeof ProtectedAdminOrganizationsRouteWithChildren
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminAuditRoute: ProtectedAdminAuditRoute,
  ProtectedAdminOrganizationsRoute:
    ProtectedAdminOrganizationsRouteWithChildren,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedOrganizationsOrganizationSlugTeamsRouteChildren {
  ProtectedOrganizationsOrganizationSlugTeamsTeamIdRoute: typeof ProtectedOrganizationsOrganizationSlugTeamsTeamIdRoute
  ProtectedOrganizationsOrganizationSlugTeamsIndexRoute: typeof ProtectedOrganizationsOrganizationSlugTeamsIndexRoute
}

const ProtectedOrganizationsOrganizationSlugTeamsRouteChildren: ProtectedOrganizationsOrganizationSlugTeamsRouteChildren =
  {
    ProtectedOrganizationsOrganizationSlugTeamsTeamIdRoute:
      ProtectedOrganizationsOrganizationSlugTeamsTeamIdRoute,
    ProtectedOrganizationsOrganizationSlugTeamsIndexRoute:
      ProtectedOrganizationsOrganizationSlugTeamsIndexRoute,
  }

const ProtectedOrganizationsOrganizationSlugTeamsRouteWithChildren =
  ProtectedOrganizationsOrganizationSlugTeamsRoute._addFileChildren(
    ProtectedOrganizationsOrganizationSlugTeamsRouteChildren,
  )

interface ProtectedOrganizationsOrganizationSlugRouteChildren {
  ProtectedOrganizationsOrganizationSlugAuditRoute: typeof ProtectedOrganizationsOrganizationSlugAuditRoute
  ProtectedOrganizationsOrganizationSlugMembersRoute: typeof ProtectedOrganizationsOrganizationSlugMembersRoute
  ProtectedOrganizationsOrganizationSlugSettingsRoute: typeof ProtectedOrganizationsOrganizationSlugSettingsRoute
  ProtectedOrganizationsOrganizationSlugTeamsRoute: typeof ProtectedOrganizationsOrganizationSlugTeamsRouteWithChildren
  ProtectedOrganizationsOrganizationSlugIndexRoute: typeof ProtectedOrganizationsOrganizationSlugIndexRoute
}

const ProtectedOrganizationsOrganizationSlugRouteChildren: ProtectedOrganizationsOrganizationSlugRouteChildren =
  {
    ProtectedOrganizationsOrganizationSlugAuditRoute:
      ProtectedOrganizationsOrganizationSlugAuditRoute,
    ProtectedOrganizationsOrganizationSlugMembersRoute:
      ProtectedOrganizationsOrganizationSlugMembersRoute,
    ProtectedOrganizationsOrganizationSlugSettingsRoute:
      ProtectedOrganizationsOrganizationSlugSettingsRoute,
    ProtectedOrganizationsOrganizationSlugTeamsRoute:
      ProtectedOrganizationsOrganizationSlugTeamsRouteWithChildren,
    ProtectedOrganizationsOrganizationSlugIndexRoute:
      ProtectedOrganizationsOrganizationSlugIndexRoute,
  }

const ProtectedOrganizationsOrganizationSlugRouteWithChildren =
  ProtectedOrganizationsOrganizationSlugRoute._addFileChildren(
    ProtectedOrganizationsOrganizationSlugRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedOrganizationsOrganizationSlugRoute: typeof ProtectedOrganizationsOrganizationSlugRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedOrganizationsOrganizationSlugRoute:
    ProtectedOrganizationsOrganizationSlugRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
